name = "gcs"

[namespace.service.new]
required = ["credential", "project_id"]
optional = ["default_service_pairs", "http_client_options"]

[namespace.storage.new]
required = ["name"]
optional = ["default_storage_pairs", "pair_policy", "work_dir"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size", "encryption_key"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "storage_class", "encryption_key"]

[pairs.encryption_key]
type = "byte_array"
description = "is the customer's 32-byte AES-256 key"

[pairs.default_service_pairs]
type = "DefaultServicePairs"
description = "set default pairs for service actions"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[pairs.project_id]
type = "string"

[pairs.storage_class]
type = "string"

[infos.object.meta.storage-class]
type = "string"

[infos.object.meta.encryption_key_sha256]
type = "string" 
